language: R
  - 4.2.1
env:
  matrix:
    - RVERSION=release
    - RVERSION=devel

sudo: required

warnings_are_errors: true

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
  - bash <(curl -s https://codecov.io/bash)

